### ISSUE TITLE
The size and the orientation of the NYTPhotosViewController is wrong on iOS7 when presented from a formsheet

### ISSUE THREAD

**Issue by ignazioc** [NYTimes/NYTPhotoViewer#101]
This issue is present on the `master` branch. 
When the `NYTPhotosViewController` is presented from a formsheet viewcontroller, the size and the orientation are wrong.
As you can see from the screenshot, the final size is the size of the presenting viewcontroller. And if the `NYTPhotosViewController` in landscape the orientation is still portrait.

![form_sheet](https://cloud.githubusercontent.com/assets/645715/11722500/4bcfd1a0-9f69-11e5-84a0-896571f0dbd4.PNG)
![presented](https://cloud.githubusercontent.com/assets/645715/11722508/52cbe9a8-9f69-11e5-925a-d52fa5ffab6d.PNG)

I created a sample project to demonstrate the issue here: https://github.com/ignazioc/NYTPhotoViewer/tree/ios7_testing

**Comment by hhanesand** [comment]
[The minimum `ios` version that this pod supports is `8.0`.](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer.podspec#L15)

I don't think this will be fixed if it is an ios7 only issue?

**Comment by cdzombak** [comment]
> I don't think this will be fixed if it is an ios7 only issue?

Yeah, we're working toward an iOS 8.0-only release, so this is unlikely to be fixed—at least by my team.
