### ISSUE TITLE
Close Button Missing

### ISSUE THREAD

**Issue by mattbischoff** [NYTimes/NYTPhotoViewer#102]
### Steps to Reproduce

1. Run either of the sample projects.
2. Tap the photo.

### Expected Results

An “X” button called `NYTPhotoViewerCloseButtonX` is displayed in the upper left corner of the view controller.

### Actual Results

No “X” button is displayed and the `nyt_photoViewerResourceBundle` method returns `nil`.

### Platform and OS

Tested both Swift 2 (with minor changes to get it to compile) and Objective-C sample projects as well as another project.

Xcode Version 7.2 (7C68)

**Comment by cdzombak** [comment]
We're looking into this. @Twigz isn't able to repro this issue right now, though I am. This is weird because this definitely did work for me when I was testing #80.

**Comment by cdzombak** [comment]
One avenue for investigation: when this worked, the pod was installed in the Example project with CocoaPods 0.38.2 ( https://github.com/NYTimes/NYTPhotoViewer/commit/d27f3d2d53ea9e4e4c6c0b46d719ed0f54aee720#diff-801cd3156cf43adeb08ac4958dccb4d7 ). The Example project is now broken, on CocoaPods 0.39.0 ( https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Example/Podfile.lock ).

Reviewing [the CocoaPods changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md) between those versions, https://github.com/CocoaPods/CocoaPods/issues/4065 is the only change between those versions that jumps out to me as possibly-related.

**Comment by bcapps** [comment]
I'm still seeing this issue. It can be observed in the sample project by adding `use_frameworks!` to the Podfile, running `pod install` with CocoaPods 0.39.0, and running the Swift target. I'm not sure which of those steps is the one that does it, but I've got the code on the branch [`feature/swift-framework`](https://github.com/NYTimes/NYTPhotoViewer/tree/feature/swift-framework).

**Comment by cdzombak** [comment]
without _any_ actual experimenting, I am guessing that `use_frameworks!

**Comment by cdzombak** [comment]
Do we have to use resource bundles for this? I suspect building a resource bundle as part of the Cocoapods install process will be a problem for Carthage support #61/#63.

I would be totally fine with moving to some other system and ignoring whatever annoying warning Cocoapods gives us about not using `resource_bundles`. Based on our experience so far they're nothing but unreliable trouble, and I've found effectively no documentation about how we're expected to use them, and I'm tired of this.

**Comment by bcapps** [comment]
@cdzombak Using `bundleForClass` instead of `mainBundle` to retrieve the resources bundle fixed the issue for me on this same branch. Check commit [`47b6240e430282f0a0358b7034b35792cdfaad52`](https://github.com/NYTimes/NYTPhotoViewer/commit/47b6240e430282f0a0358b7034b35792cdfaad52) to see it working. I haven't tested this change without frameworks or in Objective-C, but the results are preliminarily promising anyway.

**Comment by cdzombak** [comment]
> Using `bundleForClass` instead of `mainBundle` to retrieve the resources bundle fixed the issue for me on this same branch. 

Huh, that definitely makes sense, and that would explain why `use_frameworks` results in different behavior.

> Additionally, it might be a good idea to update the bundle calls to use the URL methods instead of the stringly-typed path ones.

Should make no difference whatsoever, but :+1:

**Comment by liruqi** [comment]
Cannot remove use_frameworks! in Swift. So changing Podfile like this could fix this issue?
 pod 'AFNetworking', :git => 'https://github.com/NYTimes/NYTPhotoViewer', :branch => 'develop'
