### ISSUE TITLE
Is It Possible To Remove The Share Button On Top Right For Certain Images? (Swift) 

### ISSUE THREAD

**Issue by Kkhattab** [NYTimes/NYTPhotoViewer#105]
Using this in my app, wanted to know how I can remove the share icon for certain images depending what class I am using them in.

**Comment by Kayoto1** [comment]
You can override it by set : rightBarButtonItem = nil;

**Comment by Kkhattab** [comment]
wow thank you @Kayoto1 

`   let photosViewController: NYTPhotosViewController = NYTPhotosViewController(photos: [photoType])
            photosViewController.rightBarButtonItem = nil`

this solved it

**Comment by vijayvir** [comment]
this work for me 
 

  

       class QLSPreviewController : QLPreviewController {
        
            override func viewDidLoad() {
                super.viewDidLoad()
           
                
               
            }
            override func viewWillAppear(_ animated: Bool) {
                super.viewWillAppear(animated)
                
            }
            override func viewDidAppear(_ animated: Bool) {
                super.viewDidAppear(true )
                //This hides the share item
                let add =  self.childViewControllers.first as! UINavigationController
                let layoutContainerView  = add.view.subviews[1] as! UINavigationBar
                 layoutContainerView.subviews[2].subviews[1].isHidden = true
        
            }
        }
