### ISSUE TITLE
init methods should have a delegate parameter

### ISSUE THREAD

**Issue by livings124** [NYTimes/NYTPhotoViewer#110]
The init methods call commonInitWithPhotos:initialPhoto:, which call setupPageViewControllerWithInitialPhoto:, which calls newPhotoViewControllerForPhoto:, which accesses the delegate. Currently there's no way for the delegate to be set at that point.

**Comment by bcapps** [comment]
This seems like it may be a duplicate of https://github.com/NYTimes/NYTPhotoViewer/issues/95

**Comment by cdzombak** [comment]
> This seems like it may be a duplicate of #95

with different words, but yes, that's true.
