### ISSUE TITLE
New Cocoapods/Github Release Version

### ISSUE THREAD

**Issue by bcapps** [NYTimes/NYTPhotoViewer#118]
It would be nice to have all the recent changes released in a new Cocoapods version / Github release since the current release was the [first public one](https://github.com/NYTimes/NYTPhotoViewer/releases/tag/0.1.2) in March of 2015. Pointing to a specific commit works but isn't the most ideal scenario and doesn't reflect how much has changed in the repo and the scope of those changes with semantic versioning. It seems like there might be a great opportunity to create a new release after https://github.com/NYTimes/NYTPhotoViewer/pull/114 is merged.

**Comment by cdzombak** [comment]
Thanks for bringing this up, @bcapps. Internally we are looking at tagging a 1.0.0 release once we're confident that #102 (close button missing) is totally resolved.

Ideally such a major release would include a fix for #109 and Carthage support (#61)—our team is getting close to fully understanding what's required for us to support Carthage properly. But we probably won't consider either of these blocking for a 1.0 release.

**Comment by bcapps** [comment]
Cool! Godspeed on testing that close button.

**Comment by cdzombak** [comment]
[1.0.0](https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.0.0) has been released: https://cocoapods.org/pods/NYTPhotoViewer
