### ISSUE TITLE
delegate method didDisplayPhoto doesn't get called for first photo

### ISSUE THREAD

**Issue by ipedro** [NYTimes/NYTPhotoViewer#119]
Currently this method is only called when there's a pageView change, from:

`- (void)pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:`

Ideally would be called as well from:

 `- (void)setupPageViewControllerWithInitialPhoto:`

**Comment by cdzombak** [comment]
closing as a duplicate of #95
