### ISSUE TITLE
Conditionally Disable Hack

### ISSUE THREAD

**Issue by bcapps** [NYTimes/NYTPhotoViewer#131]
It appears that radar #20070670 was fixed in the final release of iOS 8.3, although it was not marked as such on bugreport.apple.com. We should add a conditional check to [the method](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Pod/Classes/ios/NYTPhotoDismissalInteractionController.m#L138) that determines whether the radar is fixed, returning YES for iOS 8.3 or later. Feel free to test this by returning YES from the method in question and running on iOS 8.2 and 8.3 simulators (and any additional ones you want).

**Comment by cdzombak** [comment]
> It appears that radar #20070670 was fixed in the final release of iOS 8.3

Do you have an openradar or similar link, @bcapps?
