### ISSUE TITLE
Dismiss bug created in commit c0c2040

### ISSUE THREAD

**Issue by eeallen1** [NYTimes/NYTPhotoViewer#134]
By swapping the logic to fix the previous dismissal bug to make interactive dismissals properly call the delegate methods in c0c2040, it looks like it created the same bug for dismissing via the X button in the top left of NYTPhotosViewController. Now, when I swipe to dismiss, the delegate DidDismiss or WillDismiss are called, but not when I click that button.

**Comment by cdzombak** [comment]
duplicates #129 which is fixed on `develop` as of #130. We'll have a patch bugfix release out for that soon.
