### ISSUE TITLE
Ability to add photos after init

### ISSUE THREAD

**Issue by livings124** [NYTimes/NYTPhotoViewer#140]
We want to build infinite scroll in the photo viewer, meaning that we want to download more photos as we scroll through the photos, making it seem like they were all there all along. This requires being able to add photos after init.

**Comment by cdzombak** [comment]
After some internal discussion, I'm closing this in favor of #163, which is our plan to provide a more Cocoa-like API for this component.

**Comment by kimar** [comment]
This totally makes sense :+1: Thanks a bunch!
