### ISSUE TITLE
How I can init the NYTPhotosViewController with an image?

### ISSUE THREAD

**Issue by thefronter** [NYTimes/NYTPhotoViewer#144]
To init the NYTPhotosViewController I have a NYTPhoto array, but how i can get a NYTPhoto from a single image. 
I am using a collectionView and when i touch a cell i want to show the cell's picture in a NYTPhotoController, but i dont know how i can cast the normal image into a NYTPhoto. I am using Swift 2 and install NYTPhotoViewer using cocapods and use_frameworks
func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
let cell = collectionView.cellForItemAtIndexPath(indexPath) as! PortadaCollectionViewCell
let image = cell.portadaImagenView.image

 let photosViewController  = NYTPhotosViewController(photos: <[NYTPhoto]?>))
  presentViewController(photosViewController, animated: true, completion: nil)
}
Regards

**Comment by cdzombak** [comment]
> …how i can get a NYTPhoto from a single image. 
> …but i dont know how i can cast the normal image into a NYTPhoto

[`NYTPhoto` is a simple protocol](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Pod/Classes/ios/Protocols/NYTPhoto.h). You'll need to create a class that conforms to that protocol — let's call it `PortadaPhoto`. (or, if your app has an existing model class for photos, that class should adopt the `NYTPhoto` protocol). In this `PortadaPhoto` class, return your normal `UIImage` for the `image` property.

In your `NYTPhotosViewController(photos:)` call, then, pass an array containing one or more instances of `PortadaPhoto`.
