### ISSUE TITLE
Image can't zoom

### ISSUE THREAD

**Issue by happiehappie** [NYTimes/NYTPhotoViewer#159]
This is the image I'm using
http://www.getfingers.com/files/posts/56/src.jpeg
It shows that I have a minimum zoom scale of 1 and maximum zoom scale of 1 hence not allowing me to zoom

**Comment by cdzombak** [comment]
`maximumZoomScale` is determined based on the size of the image relative to the size of the scaling image view. In your case the image is smaller in pixel width than [an iPhone 6](http://www.paintcodeapp.com/news/iphone-6-screens-demystified), so not being to zoom it is expected default behavior.

To customize this, use the [`-photosViewController:maximumZoomScaleForPhoto:`](https://github.com/NYTimes/NYTPhotoViewer/blob/b04b273168f697097511384fe30b7c4dfbc1bac8/Pod/Classes/ios/NYTPhotosViewController.h#L221) delegate method.

In the future, when reporting a perceived bug, more information including your device and iOS version would be useful.

**Comment by happiehappie** [comment]
`
    let nytPhoto = PostNYTPhoto(image: photo, imageData: nil, placeholderImage: nil, attributedCaptionTitle: nil, attributedCaptionSummary: nil, attributedCaptionCredit: nil)
                let imageViewer = NYTPhotosViewController(photos: [nytPhoto])
                imageViewer.delegate = self
                imageViewer.rightBarButtonItem = nil
`
The above is my code, unfortunately 
`
    func photosViewController(photosViewController: NYTPhotosViewController, maximumZoomScaleForPhoto photo: NYTPhoto) -> CGFloat {
        print("llalaa")
        return 2
    } 
`
is not getting called

**Comment by happiehappie** [comment]
Sorry if my question is too amateur though

**Comment by k3zi** [comment]
This is because the delegate is set after the view is initialized. Therefore we should add in an init that accepts a delegate.

**Comment by cdzombak** [comment]
@happiehappie is the image you can't zoom the first or only image in the photos view controller?

If so, @k3zi is right, and you should upgrade to release [1.1.0](https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.1.0) and use the new designated initializer introduced in https://github.com/NYTimes/NYTPhotoViewer/pull/155 .

**Comment by cdzombak** [comment]
_Closing for now; @happiehappie, please reopen if using the new initializer, with a delegate, doesn't fis this for you._
