### ISSUE TITLE
Itunes Connect rejected binary after update to 1.1.0

### ISSUE THREAD

**Issue by sepandb** [NYTimes/NYTPhotoViewer#161]
The app references non-public selectors in MYAPP: hide:, initWithImages:, initWithPhotos:, remoteURL, setDataTypes:, setLabelText:, setReferenceView:, setTextBackgroundColor:, setTransitionStyle:, stopVideo

After I downgraded to 1.0.1 I was approved - just wanted to point this out.

**Comment by manijak** [comment]
@sepandb  @cdzombak 
Is this still an issue, are we able to publish apps with version 1.1.0?

**Comment by cdzombak** [comment]
I'm not convinced that PhotoViewer is causing your problem. Of the selectors you list, only `initWithPhotos:` is part of NYTPhotoViewer, and it is present in both version 1.0.1 and 1.1.0 (v [1.1.0](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/CHANGELOG.md#110) was not a very big change) so I am not sure why downgrading would have fixed your problem.

@manijak are you seeing this submission problem too?

**Comment by manijak** [comment]
@cdzombak , no I can't say I do. I am getting close to publishing my app that uses this pod so just wanted to know if this was a known issue or not. Thanks!

**Comment by manijak** [comment]
@cdzombak just to confirm, there are no issues with the pod when it comes to release. My app just got released without issues using this pod. 

Btw: I hope you don't mind, but I also created a nativescript-version of your pod, it's for the framework that we use to create cross-platform apps. 
https://www.npmjs.com/package/nativescript-photoviewer

**Comment by cdzombak** [comment]
@manijak interesting; thanks for the link! And thanks for confirming your app was accepted without issues.
