### ISSUE TITLE
README--The guide of the swift is error

### ISSUE THREAD

**Issue by cijianzy** [NYTimes/NYTPhotoViewer#174]
In README.MD

the method to import NYTPhotoViewer in swift is error.

forgive my English.

**Comment by cdzombak** [comment]
I removed the outdated text referring to manually creating a bridging header in https://github.com/NYTimes/NYTPhotoViewer/commit/4d81aac9e6429be4b9bc011d3453e3884a41e3fb .

If you're referring to something else, please reopen this issue with more detail on what needs to be corrected. Thank you!
