### ISSUE TITLE
Broken on Cocoapods 1.0.0 beta 6

### ISSUE THREAD

**Issue by danielgalasko** [NYTimes/NYTPhotoViewer#175]
I am hoping to start a conversation here so that we can direct this at the cocoapods team, but right now using the latest beta `NYTPhotoViewer` doesn't build and instead outputs the following error:

    error: /Users/Path/To/Build/Products/Debug-iphonesimulator/NYTPhotoViewer/NYTPhotoViewer.bundle: No such file or directory

This works on the latest release of cocoapods (0.39.0 I think) but on the betas its broken. 

It seems to me that cocoapods has broken the usage of `resource_bundle` (used [here](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer.podspec#L19)) in the new releases.

Funnily enough Google use the `resources` property ([here](https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAppIndexing/2.0.3/GoogleAppIndexing.podspec.json)) and this seems to be working.

I will submit a bug with cocoapods but I thought it should have visibility here too

**Comment by danielgalasko** [comment]
Submitted an issue https://github.com/CocoaPods/CocoaPods/issues/5034

**Comment by danielgalasko** [comment]
For anyone running into this issue you can use [my fork](https://github.com/danielgalasko/NYTPhotoViewer) which uses the `resource` Spec syntax instead as this is working

**Comment by cdzombak** [comment]
Thanks for digging into this and filing https://github.com/CocoaPods/CocoaPods/issues/5034 , @danielgalasko.

Given that this _seems_ right now to be a problem in the latest CocoaPods beta, and that as noted in https://github.com/CocoaPods/CocoaPods/issues/5034#issuecomment-197309418 the `resource_bundle` approach is strongly recommended, this seems like something that doesn't require action on our part right now (though I'll leave this open to track developments while that CocoaPods issue is resolved). Does that sound right to you?

**Comment by danielgalasko** [comment]
Yip, that's why I created the issue. Will keep an eye on the official
thread and then you can close this when the CocoaPods team resolves it.

This is just hear to help other users who have the same issue:)

**Comment by HeidiHansen** [comment]
Ohmigosh, I spent days trying to resolve this.  Rolled back to beta 5 and my project will finally build.  Thanks!

**Comment by pual** [comment]
It should work again with cocoapods 1.0.0 beta7

**Comment by cdzombak** [comment]
Once someone can confirm that CocoaPods 1.0.0 beta 7 resolves this for PhotoViewer, we'll go ahead and close this issue.

**Comment by ThibaultVlacich** [comment]
I confirm, it works!

**Comment by cdzombak** [comment]
✨ thanks for the report, @ThibaultVlacich!
