### ISSUE TITLE
Carthage update is skipping the build becuase "Dependency "NYTPhotoViewer" has no shared framework schemes"

### ISSUE THREAD

**Issue by arinjoy** [NYTimes/NYTPhotoViewer#177]
Hi, I'm not able to build the NYTPhotoViewer using "carthage update" command. It's giving me the following error.   

The main problem is **Dependency "NYTPhotoViewer" has no shared framework schemes**. 

Can you someone please look into this issue? Any help would be greatly appreciated.

Thanks.

*** Cloning NYTPhotoViewer
*** Checking out NYTPhotoViewer at "1.1.0"
*** xcodebuild output can be found in /var/folders/9_/nxpbqcfs3kz90t5z0k8rk_2c0000gq/T/carthage-xcodebuild.yMwKGV.log
*** Skipped building NYTPhotoViewer due to the error:
Dependency "NYTPhotoViewer" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/NYTimes/NYTPhotoViewer/issues/new

**Comment by cdzombak** [comment]
> *** Checking out NYTPhotoViewer at "1.1.0"

Have you checked out the most recent `develop` branch? Carthage support was only added 2 weeks ago and hasn't been formally released with a version number yet.

Per https://github.com/NYTimes/NYTPhotoViewer/issues/61#issuecomment-193370167 : 

> This is a large change and before we cut an official release, I'd appreciate it if those who have expressed interest in this support could try this out (`github "NYTimes/NYTPhotoViewer" "develop"`) and see how it works for them.

Try telling Carthage to checkout `develop` specifically.

**Comment by arinjoy** [comment]
Thank you so much! It worked when I used the github "NYTimes/NYTPhotoViewer" "develop".

**Comment by RSully** [comment]
Just thought I'd say I'm having this issue now too. Using develop works, but maybe it shouldn't be in master's readme until it is merged?
