### ISSUE TITLE
Is it possible to customize the NYTPhotoViewer nav bar without messing with the NYTPhoto Pod's Core code?

### ISSUE THREAD

**Issue by ChristinaLeuci** [NYTimes/NYTPhotoViewer#180]
Using this in my app, wanted to know how I can customize the navigation bar to show an additional rightBarButtonItem without messing with the Pod's Core code.

**Comment by cdzombak** [comment]
Offhand, I think [the `rightBarButtonItems` property on `PhotosViewController`](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer/NYTPhotosViewController.h#L84) is what you're looking for. Can you experiment with that and see if that'll meet your needs?

**Comment by ChristinaLeuci** [comment]
Perfect, thanks!
