### ISSUE TITLE
how can i update the image in didNavigateToPhoto method

### ISSUE THREAD

**Issue by tanishajain** [NYTimes/NYTPhotoViewer#189]
photo.image = xyz gives the error "Cannot assign to property: 'image' is a get only property"

**Comment by cdzombak** [comment]
Can you use [the `-updateImageForPhoto:` method](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer/NYTPhotosViewController.h#L134) to achieve your goal?

**Comment by tanishajain** [comment]
I tried but that also didn't work

**Comment by elburro1887** [comment]
I guess you are trying to load the photo "lazily" when the user navigates to the specific photo. 

The way I solved it, is to make the photo loading operation trigger a notification upon completion.
This notification then calls a function that updates the current image.

```
- (void)updateCurrentSwipePhoto:(NSNotification *)notification {
  id <NYTPhoto> photo = [notification object];
  
  if(self.nytPhotoVC) {
    [self.nytPhotoVC updateImageForPhoto:photo];
  }
}
```

Note that you need to keep a reference to the NYTPhotosViewController instance.

**Comment by tanishajain** [comment]
Thank you so much for the solution..
