### ISSUE TITLE
Intermittent "Glitchy" Captions When Swiping Between Photos

### ISSUE THREAD

**Issue by mliberatore** [NYTimes/NYTPhotoViewer#19]
On my iPhone 6 Plus while testing in newsreader, I've intermittently seen the text below the photo in a slideshow appear glitchy (jumping from being aligned at the bottom to above that position quickly back and forth) when swiping between the first and second photo. It's inconsistent, and not definitive, but I've only seen this happen after scrolling the article before tapping the slideshow.

**Comment by bcapps** [comment]
@mliberatore Do you still see this behavior on your 6 Plus after the new `UITextView` caption changes?

**Comment by mliberatore** [comment]
@bcapps sorry, that device is not currently in working condition. I believe we have a test device in the office, though (cc @Twigz to help prioritize testing/fixing).

**Comment by bcapps** [comment]
@mliberatore RIP 6 Plus. You were too large for your own good.

**Comment by mliberatore** [comment]
:stuck_out_tongue:
