### ISSUE TITLE
Bridging Header Example Link Broken

### ISSUE THREAD

**Issue by kbpontius** [NYTimes/NYTPhotoViewer#191]
On the main page of this library, there is a link for the text "this one from the sample Swift project". It should be taking you to an example of the bridging header you'd use in Swift to import the project. This link, however, doesn't work, and brings up a Github 404 page. Please fix.

**Comment by kwstasna** [comment]
Still the same

**Comment by cdzombak** [comment]
If you're integrating via CocoaPods or Carthage, I don't think this is something you need to worry about. That text is leftover from ages ago.

https://github.com/NYTimes/NYTPhotoViewer/commit/4d81aac9e6429be4b9bc011d3453e3884a41e3fb
