### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by gilesvangruisen** [NYTimes/NYTPhotoViewer#195]
Thanks for this library!! 

It looks like there hasn't been a new release since February, and in that time there's been good progress including adding support for Carthage. 

Unfortunately, because there has been no new release, the README's instructions for installing via Carthage are a bit stale. Carthage will automatically fetch the latest release if you list `github "NYTimes/NYTPhotoViewer"` in the `Cartfile`. This works for fetching, however Carthage is unable to build because the latest release doesn't include Carthage support.

As a workaround, I can add `github "NYTimes/NYTPhotoViewer" "develop"` to ensure Carthage fetches the latest `master`, but this is unclear and potentially unstable.

Are there plans to publish a new release soon?

**Comment by cdzombak** [comment]
Carthage support has now been pushed to `master` and tagged as `1.2.0`.

https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.2.0
