### ISSUE TITLE
Install failed with Carthage

### ISSUE THREAD

**Issue by nixzhu** [NYTimes/NYTPhotoViewer#197]
carthage update NYTPhotoViewer

```
*** Skipped building NYTPhotoViewer due to the error:
Dependency "NYTPhotoViewer" has no shared framework schemes
```

**Comment by hainguyen86** [comment]
confirmed :( it doesn't work

**Comment by absolutlabs** [comment]
Actually you can build the framework if you download (zip) the sources.

`github "NYTimes/NYTPhotoViewer"` downloads the last tagged commit (1.1.0) from february..

**Comment by livings124** [comment]
You have to specify the branch as "develop", since carthage support hasn't made its way into the newest released version yet.

**Comment by cdzombak** [comment]
Carthage support has now been pushed to `master` and tagged as `1.2.0`.

https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.2.0
