### ISSUE TITLE
How can I manage minimal length of pan gesture to dismiss photo?

### ISSUE THREAD

**Issue by rafalkitta** [NYTimes/NYTPhotoViewer#201]
I just want to allow user to longer vertical pan gesture before dismiss photo.

**Comment by jamesstout** [comment]
It's determined by this line: https://github.com/NYTimes/NYTPhotoViewer/blob/533a1fa40d0d4d518df737b76318715408050b74/NYTPhotoViewer/NYTPhotoDismissalInteractionController.m#L11

And used later to determine if the pan was long enough to dismiss:

https://github.com/NYTimes/NYTPhotoViewer/blob/533a1fa40d0d4d518df737b76318715408050b74/NYTPhotoViewer/NYTPhotoDismissalInteractionController.m#L54-L55

So, the pan length has to be greater than `(50/667) * fromView.bounds.height`

i.e. 

- 50 on iPhone 6/7/8
- 60.869565 on iPhone X
- 55.172414 on the Plus models

etc etc

If you're not worried about editing the original source code you can change the 50 in [L11](https://github.com/NYTimes/NYTPhotoViewer/blob/533a1fa40d0d4d518df737b76318715408050b74/NYTPhotoViewer/NYTPhotoDismissalInteractionController.m#L11) to something larger, alternatively, request (or submit a PR) changing `NYTPhotoDismissalInteractionControllerPanDismissDistanceRatio` to a settable property, although there may be reasons why it's a static const that I'm not aware of.

You can see how much of a faff it would be to expose it as a property: https://github.com/jamesstout/NYTPhotoViewer//compare/develop...jamesstout:PanDismissDistance-property

**Comment by rafalkitta** [comment]
Thank you for your response, very helpful 😉
