### ISSUE TITLE
AppDelegate application:supportedInterfaceOrientationsForWindow: doesn't call on controller dismiss

### ISSUE THREAD

**Issue by wowbroforce** [nytimes/NYTPhotoViewer#202]
Hi!

I'm trying to implement orientation change for single controller while the application itself stays in portrait mode. For this purpose I'm using AppDelegate's method `application:supportedInterfaceOrientationsForWindow:`:

```
    func application(application: UIApplication, supportedInterfaceOrientationsForWindow window: UIWindow?) -> UIInterfaceOrientationMask {
        if let controller = AppRouter.topViewController() as? NYTPhotosViewController {
            return .All
        }
        return .Portrait
    }
```

When controller is presented - all works fine. But the problem is that the method doesn't called when controller is dismissing and the app stays in landscape mode after controlled is dismissed.
If I set controller's `transitioningDelegate` with my test transition instead of your cool custom one, than AppDelegate will be called as expected, so I think the problem is related to transition. I will continue to investigate this issue, but maybe you can tell me how to fix this quickly. 
If you need any additional info - just ask.
Thanks!

**Comment by simonemarinelli** [comment]
+1
