### ISSUE TITLE
Dependency "NYTPhotoViewer" has no shared framework schemes

### ISSUE THREAD

**Issue by 18612031364** [NYTimes/NYTPhotoViewer#204]

**Comment by carlos19932001** [comment]
See #197 
can you use specific branch
`github "NYTimes/NYTPhotoViewer" "develop"`

**Comment by thanhdevapp** [comment]
i have same problem, whay author not update document, thanks @carlos19932001

**Comment by cdzombak** [comment]
Carthage support has now been pushed to `master` and tagged as `1.2.0`.

https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.2.0
