### ISSUE TITLE
Swift - Cannot update image for NYTPhoto instance

### ISSUE THREAD

**Issue by haithngn** [NYTimes/NYTPhotoViewer#210]
Because image is a read only property, so after retrieve image data from network I cannot update for the NYTPhoto

```
/**
     *  The image to display.
     *
     *  This property is used if and only if `-imageData` returns `nil`. Note, however, that returning `UIImage`s from this property whenever possible will result in better performance. See `-imageData`'s documentation for discussion.
     */
    @available(iOS 2.0, *)
    public var image: UIImage? { get }
```

 cannot assign to property: 'image' is a get-only property

**Comment by cdzombak** [comment]
`NYTPhoto` is just a protocol which specifies that the photo viewer must be able to read an `image` from whatever object your application conforms to `NYTPhoto`. Your application must define an object conforming to that protocol, and it can make that property read-write if desired. (You could also define some other way to mutate the photo, without exposing that property as read-write.)

In one Swift application, I have an object that conforms to `NYTPhoto` like this:

```final class NYTPhotoBox: NSObject, NYTPhoto {
    // …

    // MARK: NYTPhoto

    var image: UIImage?
    var imageData: Data?
    var placeholderImage: UIImage?

    // …
}
```

In this example, all `NYTPhoto` properties are mutable.
