### ISSUE TITLE
PhotoViewer with array image urls

### ISSUE THREAD

**Issue by iMark21** [NYTimes/NYTPhotoViewer#216]
Im not able to load asynchronously images on this framework, can anyone help me? Im using AFNetworking to load that kind of images. (Maybe some example it could be better)

**Comment by JurayevNodir** [comment]
@interface NYTExamplePhoto : UIImageView <NYTPhoto>
and remove image property from class )

**Comment by maciejzukowski** [comment]
https://github.com/NYTimes/NYTPhotoViewer/issues/203#issue-166349885

**Comment by cdzombak** [comment]
Unfortunately, we don't plan to support this in this library at this time. This feature would require this UI component to handle fetching and caching, or otherwise dictate a third-party library for those tasks, which we feel is better left to another part of your application.
