### ISSUE TITLE
setAction to leftBarItems

### ISSUE THREAD

**Issue by JurayevNodir** [NYTimes/NYTPhotoViewer#218]
Hello! I need customization leftBarItems. Can I set action for dissmissViewController ? 
Thanks!

**Comment by bcapps** [comment]
Hey @JurayevNodir. There is a [`leftBarButtonItems`](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer/NYTPhotosViewController.h#L74) property on `NYTPhotosViewController` that will allow you to fully customize the left bar button items and their actions. Thanks for your question!

**Comment by JurayevNodir** [comment]
I can not fix this bug. http://joxi.ru/L210eVws6PkjLm  Can you help me?

**Comment by JurayevNodir** [comment]
@bcapps  can I set action to custom leftBarItem ?

**Comment by bcapps** [comment]
>@bcapps can I set action to custom leftBarItem ?

[Yes](https://github.com/NYTimes/NYTPhotoViewer/issues/218#issuecomment-255226029), you can set your own, fully custom left bar button item, on which you can set any action.

**Comment by JurayevNodir** [comment]
I need action doneButtonTapped:. bad this  private method. I'm using pods ) and can't change to public method
