### ISSUE TITLE
Pod and Example difference

### ISSUE THREAD

**Issue by ekazaev** [NYTimes/NYTPhotoViewer#231]
Could you please explain something?
I download example and i see method 
- (instancetype)initWithDataSource:(id <NYTPhotoViewerDataSource>)dataSource;

I install pod to my app and see only 
- (instancetype)initWithPhotos:(id <NYTPhoto>)photos;

Datasource is private

**Comment by cdzombak** [comment]
I'm sorry for the confusion here, @ekazaev. When you check out the example project right now, you're probably looking at the `develop` branch, which contains [some changes which haven't yet been released](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/CHANGELOG.md#develop).

If you check out the `master` branch of this repo, you'll see an example (the Objective-C one) which works with the current version of the pod.

I'll see if I can make the `master` branch the default, to prevent this confusion in the future.
