### ISSUE TITLE
Swift error NYTPhotosViewController

### ISSUE THREAD

**Issue by DennisMostajo** [NYTimes/NYTPhotoViewer#232]
Hi everyone Im using Xcode 8.2.1
  ```
func touchImageAction(_ myImage: UIImage)
  {
        let photos = [PreviewPhoto(image: previewImage)]   // PreviewPhoto is a NYTPhoto Class
        let controller = NYTPhotosViewController(photos:photos) // here is the issue
        controller.modalPresentationStyle = .fullScreen
        
        self.view.viewController()?.present(controller, animated: true, completion: nil)
    }
```

the Error show me:

- Argument labels '(photos:)' do not match any available overloads
- Overloads for 'NYTPhotosViewController' exist with these partially matching parameter lists: (dataSource: NYTPhotoViewerDataSource), (coder: NSCoder)

How Can I Fix It?, please Thanks!

**Comment by hanishassim** [comment]
@DennisMostajo did you found the solution for this? I'm experiencing the same problem..

**Comment by DennisMostajo** [comment]
Hi @hanishassim, I closed this issue because meanwhile debugging I discovered that the error was when verifying that I was sending an empty or nil Image when I was calling the function, I suggest reviewing the whole process, it happened to me when I update my real device from iOS 10 to iOS 11
