### ISSUE TITLE
Setting Data Source

### ISSUE THREAD

**Issue by danielchangsoojones** [NYTimes/NYTPhotoViewer#233]
Is it possible to set the datasource on the NYTPhotosViewController? I have looked all over the example and documentation, and can not figure out a way. I am loading the image files from my backend, and then I want them to display as they are loaded, similar to how a tableview works. But, I can not figure out a way to set the datasource like: photosVC.datasource = self. Then, I could just implement the datasource methods. Is this possible?

**Comment by cdzombak** [comment]
Take a look at [the `develop` branch](https://github.com/NYTimes/NYTPhotoViewer/tree/develop) — I'd like to get a few other things done before making a release, but it includes https://github.com/NYTimes/NYTPhotoViewer/pull/226 which sounds like what you're looking for.
