### ISSUE TITLE
Automatic Slideshow / autoplay feature

### ISSUE THREAD

**Issue by tleyden** [NYTimes/NYTPhotoViewer#236]
I'm looking for something like this:

```
var nytPhotos = [NYTPhoto]()
// .. load photos 
let photosViewController = NYTPhotosViewController(photos: nytPhotos)
photosViewController.autoPlay(delay: 5s, circular: true)
present(photosViewController, animated: true, completion:nil)
```

where `.autoPlay(delay: 5s, circular: true)` would cause it to rotate through the images, with a delay of 5s and do a circular wrap.  I guess transitions would be nice too .. 

Does anything like that exist in the API or as sample code?  Would a PR be considered?  What should that look like?

**Comment by cdzombak** [comment]
> Does anything like that exist in the API or as sample code?

Nothing like this exists in the API. You should be able to do this fairly easily with a timer and [the `-displayPhoto:animated:` method](https://github.com/NYTimes/NYTPhotoViewer/blob/master/NYTPhotoViewer/NYTPhotosViewController.h#L129), cycling through the photos in the data source.

> Would a PR be considered?

Probably not, sorry. We aren't likely to use this in our application, so by merging a PR we'd be committing to maintaining an API we don't use.

**Comment by tleyden** [comment]
Ok thanks, I'll take that approach!
