### ISSUE TITLE
FLAnimatedImage/FLAnimatedImage.h file not found

### ISSUE THREAD

**Issue by sphairo** [nytimes/NYTPhotoViewer#239]
:/  #import <FLAnimatedImage/FLAnimatedImage.h>

**Comment by sean808080** [comment]
Adding FLAnimatedImage project manually to this project builds successfully but crashes with a dyld`__abort_with_payload error.

**Comment by pts011080** [comment]
FLAnimatedImage is for GIF image display.
If GIF image is not your required enquiries, consider to bypass it.
You can remove ANIMATED_GIF_SUPPORT=1 flag from NYTPhotoViewer project's build setting to avoid the compiling error.

**Comment by krzysztofzablocki** [comment]
we moved to PINRemoteImage
