### ISSUE TITLE
Version 2.0.0 not installing

### ISSUE THREAD

**Issue by OkiRules** [NYTimes/NYTPhotoViewer#252]
When I try to install it through cocoa pods it says NYTPhotoViewer(1.2.0) as the latest version?

Has it come through on to the cocoaPods server yet if there is one?

**Comment by jamesstout** [comment]
Cocoapods repo not updated yet: https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/d/NYTPhotoViewer

This might work for the moment:

`pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer.git', :tag => 'v2.0.0'`

**Comment by jamesstout** [comment]
However, I'm not sure it's quite ready. The tests have not been updated. Some of the docs are wrong also.

**Comment by OkiRules** [comment]
Could you please fix them?

**Comment by OkiRules** [comment]
I got it working with your code above "pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer.git', :tag => 'v2.0.0'" but i shouldn't need to do that please update the the code.

Thanks Anyway

**Comment by jamesstout** [comment]
It’s not my repo - we’ll have to wait for one of the maintainers to publish the updated spec to cocoapods. 

You could always try fixing the tests yourself. That’s what I did, will see if it’s accepted: https://github.com/NYTimes/NYTPhotoViewer/pull/253

**Comment by OkiRules** [comment]
Great thanks

----------
Thanks
Oscar Gorog

**Comment by Mardoxx** [comment]
`pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer.git', :tag => 'v2.0.0'`

nor working for us, `pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer.git', :tag => '2.0.0'`

is, however..

**Comment by jamesstout** [comment]
Maybe the tag was changed. Anyway, no need now as the 2.0.0 podspec has been pushed to cocoapods.org: https://github.com/NYTimes/NYTPhotoViewer/pull/249#issuecomment-360916673
