### ISSUE TITLE
NYTPhotosViewController crashes on tapping Share button on iPad

### ISSUE THREAD

**Issue by mpkeefe** [NYTimes/NYTPhotoViewer#28]
I made a sample app (PRs: #25 #27) in Swift that mimics the current example ObjC app and runs on both iPhone and iPad, using the built-in NYTPhotosViewController.  On iPad, the ShareActivityViewController crashes because it needs to be presented inside a popover. This can be done in iOS 8 simply by setting `shareActivityViewController.popoverPresentationController?.barButtonItem` but on iOS 7 will need to wrap inside a `UIPopoverController` I guess.  Are there any other considerations?

**Comment by cdzombak** [comment]
The Swift example project is iOS 8-only, I believe, and the Share button works fine on the iPad Simulator.

The ObjC example app currently doesn't seem to work on the iPad at all :/

**Comment by heikkihautala** [comment]
Created a PR for this: https://github.com/NYTimes/NYTPhotoViewer/pull/52.
