### ISSUE TITLE
cannot install version 3.o from cocoapods

### ISSUE THREAD

**Issue by harishchopra86** [nytimes/NYTPhotoViewer#289]
Installing from cocoa pods always installs version 2.0 and never installs latest version 3.0.0 or 3.0.1. I even tried specifying version but no success

**Comment by jamesstout** [comment]
The latest podspecs have not been published: https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/d/NYTPhotoViewer

**Comment by rsimenok** [comment]
@atecle Sorry, can you help with this?

**Comment by harishchopra86** [comment]
@rsimenok I have installed latest version by specifying the commit, you can try this. I had used below line in podfile:
  pod 'NYTPhotoViewer', :git => 'https://github.com/nytimes/NYTPhotoViewer.git', commit: 'a98345768850ea4902c61986498cebc2af8069e7'

You can change the commit number to reflect latest commit.

**Comment by racer1988** [comment]
+1, Pod Spec is missing

**Comment by mr-fixit** [comment]
is this still happening for people?  
if so, have you tried `pod repo update` or `bundle exec pod repo update`?
