### ISSUE TITLE
Does the library support loading a remote image

### ISSUE THREAD

**Issue by dlpigpen** [nytimes/NYTPhotoViewer#308]
I've digged into the library but it seems only support a local image. Can we support loading a remote image?  

How about the scroll to page at index?

**Comment by mr-fixit** [comment]
### does it support loading a remote image?
yes, but probably not like you mean.  

you download the image yourself, using whatever network and caching mechanism you chose, then call `updatePhoto:` or `updatePhotoAtIndex:`.

### does it support 'scroll to page at index'?

not yet, but we'd welcome a PR.
