### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by karimhm** [nytimes/NYTPhotoViewer#320]
This library have a memory leak, `-[NYTPhotosViewController dealloc]` is never called.

**Comment by mr-fixit** [comment]
I tried to reproduce, but couldn't.

I ran the example app, tapped the picture (creating an NYTPhotosViewController), then the X in the upper left corner, and saw  `-[NYTPhotosViewController dealloc]` called.

If you can reproduce, please give the details about how to reproduce, including a link to the source code.
