### ISSUE TITLE
Xcode 12 build fails due to PINCache error

### ISSUE THREAD

**Issue by richieWave** [nytimes/NYTPhotoViewer#321]
I know this is not properly a NYTPhotoViewer issue but, since it uses that library, it is unable to build in Xcode 12 since PINCache fails.

**Comment by sgbasaraner** [comment]
I also have the same issue with Xcode 12 Beta 4
2 compilation errors for me:

Pods/PINCache/Source/PINCache.m:121:62: error: incompatible block pointer types sending 'void (^)(PINMemoryCache *__strong, NSString *__strong, __strong id)' to parameter of type 'PINCacheObjectBlock _Nonnull' (aka 'void (^)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)')
        [self->_memoryCache objectForKeyAsync:key completion:^(PINMemoryCache *memoryCache, NSString *memoryCacheKey, id memoryCacheObject) {


Pods/PINCache/Source/PINCache.m:274:64: error: incompatible block pointer types sending 'void (^)(PINDiskCache *__strong)' to parameter of type 'PINCacheBlock _Nonnull' (aka 'void (^)(id<PINCaching>  _Nonnull __strong)')
    [_diskCache synchronouslyLockFileAccessWhileExecutingBlock:^(PINDiskCache *diskCache) {

**Comment by sgbasaraner** [comment]
https://github.com/pinterest/PINRemoteImage/issues/559#issue-674563539

**Comment by sgbasaraner** [comment]
PINRemoteImage just released a new version that fixed the issue.

**Comment by petarbelokonski** [comment]
There you go https://github.com/nytimes/NYTPhotoViewer/pull/324

**Comment by repomies** [comment]
I'm still having this issue with the new Xcode 12 GM seed. I simply have `pod 'NYTPhotoViewer'` in my Podfile and it fails to build because it still keeps installing the old `PINCache (3.0.1-beta.8)` from 2019 instead of the new 3.0.1 release.

**Comment by mr-fixit** [comment]
on it!

**Comment by mr-fixit** [comment]
this will be fixed by PR #330

**Comment by mr-fixit** [comment]
fixed in 5.0.4
