### ISSUE TITLE
build issue with 5.0.4

### ISSUE THREAD

**Issue by mr-fixit** [nytimes/NYTPhotoViewer#331]
i broke something. 

carthage now says:

`Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Carthage/Checkouts/libwebp) but encountered: 
`

xcode is missing `NYTPhotoViewer/Carthage/Build/iOS/PINRemoteImage.framework`

**Comment by choli** [comment]
Hello, ended up in the same issue when trying to update to 5.0.4/5.0.5. Is there an issue with carthage and submodules that is not handled properly?

**Comment by mr-fixit** [comment]
in a word, yes. 

i think the fix is to convert the project from being assembled in the Carthage way, where the project file points to frameworks in Carthage/Build, to the Cocoapods way, where `pod install` will generate the xcworkspace and touch the xcproject file.

i made a start on that a week ago, but got distracted by higher priorities. 

i'd be happy to review someone else's PR, if they get to it first.
