### ISSUE TITLE
Swift Package Manager support (SPM)

### ISSUE THREAD

**Issue by SirWellington** [nytimes/NYTPhotoViewer#332]
Are there any plans to provide support for SPM?

**Comment by GertjanSmits** [comment]
I'd also like that, this package is the only one that prevents me from removing the Podfile :)

**Comment by cassianodialpad** [comment]
@mr-fixit When trying to add this package, I'm getting the error `https://github.com/nytimes/NYTPhotoViewer has no Package.swift manifest for version 5.0.5`. Adding the `develop` branch works though.

Could you please make this available in a released version? Thanks!

**Comment by mr-fixit** [comment]
Hi Cassiano! Thanks for mentioning this. I've just now tagged the head of `develop` with `5.0.6`, and was able to add it to a test project...

<image src='https://user-images.githubusercontent.com/325572/106527192-e099d180-64b4-11eb-96f7-c06e19ae96ce.png' width='500'>

**Comment by cassianodialpad** [comment]
@mr-fixit Great, thanks!
