### ISSUE TITLE
Jump into specific NYTPhoto

### ISSUE THREAD

**Issue by socheat1994** [nytimes/NYTPhotoViewer#337]
I worked with NYTPhotoViewer, and I also integrated it successfully with the simple one. Anyway, I am trying to jump to the specific NYTPhoto. 
Example: I want to view the NYTPhoto 3 of 5 instead of 1 of 5. 
Do you have any idea with this problem? The doc is not friendly. :|

**Comment by mr-fixit** [comment]
if you want to start the viewer at a specific photo, e.g. `3`, do

```
- (instancetype)initWithDataSource:(id <NYTPhotoViewerDataSource>)dataSource initialPhotoIndex:(NSInteger)initialPhotoIndex delegate:(nullable id <NYTPhotosViewControllerDelegate>)delegate;
```

if you want to tell the viewer to go to a specific index after it has started, you could call this:
```
/**
 *  Displays the specified photo. Can be called before the view controller is displayed. Calling with a photo not contained within the data source has no effect.
 *
 *  @param photo    The photo to make the currently displayed photo.
 *  @param animated Whether to animate the transition to the new photo.
 */
- (void)displayPhoto:(nullable id <NYTPhoto>)photo animated:(BOOL)animated;
```

**Comment by mr-fixit** [comment]
closing for now, but add a comment if the above doesn't make sense, or doesn't work ...
