### ISSUE TITLE
Add urls with photo support

### ISSUE THREAD

**Issue by andwhy** [NYTimes/NYTPhotoViewer#34]
Thanks for cool control!
We need url photo downloading and catching support

**Comment by cdzombak** [comment]
Thanks for the suggestion!

Our intention for this library is as a view-level component. That is, we don't see it as this library's responsibility to retrieve photos for you, only to display photos you've already obtained.

Downloading and caching photos can, depending on your application, be a complex problem and there are many cases we'd have to tackle here to create a generic solution. And still, many apps wouldn't use that part of the library; the NY Times app and NYT Now each handle asset management and offline support separately, for example, and apps which don't pull photos from the network (camera apps, for example) wouldn't need this functionality either.

In keeping with thinking like [the Unix philosophy](http://en.wikipedia.org/wiki/Unix_philosophy) and the [single responsibility principle](http://en.wikipedia.org/wiki/Single_responsibility_principle), we see this library's responsibility as simply displaying photos, not downloading or caching them.
