### ISSUE TITLE
Swift Package Manager GIF support

### ISSUE THREAD

**Issue by cassianodialpad** [nytimes/NYTPhotoViewer#341]
I'm adding NYTPhotoViewer to my project using SPM (from the `developer` branch). It seems it's compiled without GIF support, as I can see the log message below:

`[NYTPhotoViewer] Warning! You're providing imageData for a photo, but NYTPhotoViewer was compiled without animated GIF support. You should use native UIImages for non-animated photos. See the NYTPhoto protocol documentation for discussion.`

Apparently this is set through a preprocessor definition `ANIMATED_GIF_SUPPORT=1` (as I can see on its podspec), but apparently there is no way of adding that preprocessor flag for a SPM dependency.

Maybe this is something that should be included in the `Package.swift` file?

**Comment by cassianodialpad** [comment]
@mr-fixit Any ideas?

**Comment by mr-fixit** [comment]
Thanks for pinging me. Am just now thinking about it.

**Comment by cassianodialpad** [comment]
Thanks! For carthage, I see that `ANIMATED_GIF_SUPPORT=1` is pre-defined in the project's settings that is built in the shared scheme. If I'm correct, maybe we could add a `define` spec in `Package.swift`. From looking at the links below:
https://github.com/apple/swift-evolution/blob/master/proposals/0238-package-manager-build-settings.md
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#swiftsetting

Maybe something like this:

```
swiftSettings: [
        .define("ANIMATED_GIF_SUPPORT"),
    ],
```

* I'm not sure if this would be a swiftSettigs or a cxxSettings...

**Comment by mr-fixit** [comment]
I'm still investigating, but so far I see these potential solutions:
- have 2 targets in the package manifest, one that uses `cSettings` to turn the feature on.
- move the toggle behind a runtime, not compile-time, switch
- remove the toggle, support is always on (or off)

I think it would be nice to allow users of the library to NOT have to pull in PINRemoteImage.

**Comment by cassianodialpad** [comment]
IMO having 2 targets is very reasonable. I've seen this approach in several other packages (Google Firebase for example has a ton of targets and pulls in all their code even if you don't use them).
Having to pull in a dependency would not that bad if it's simply sitting there and it's not added to our app if not used.

Thanks for looking into that!
