### ISSUE TITLE
Missing all pods

### ISSUE THREAD

**Issue by SimonKravis** [nytimes/NYTPhotoViewer#349]
Project will not build in Xcode 12.3- Pods folder shows in red and all files in it are not found. No folder /Users/apple/Projects/NYTPhotoViewer-develop/Examples/Pods present.

Showing All Messages
/Users/apple/Projects/NYTPhotoViewer-develop/Examples/Pods/Target Support Files/Pods-Example/Pods-Example.debug.xcconfig: unable to open file (in target "Example" in project "NYTPhotoViewer")

/Users/apple/Projects/NYTPhotoViewer-develop/Examples/Pods/Target Support Files/Pods-Example/Pods-Example.debug.xcconfig: unable to open file (in target "Example" in project "NYTPhotoViewer")

/Users/apple/Projects/NYTPhotoViewer-develop/Examples/Pods/Target Support Files/Pods-Example/Pods-Example.debug.xcconfig: unable to open file (in target "Example" in project "NYTPhotoViewer")

/Users/apple/Projects/NYTPhotoViewer-develop/Examples/Pods/Target Support Files/Pods-Example/Pods-Example.debug.xcconfig: unable to open file (in target "Example" in project "NYTPhotoViewer")

**Comment by mr-fixit** [comment]
Sounds like you opened the `xcproject` file. You need to open `xcworkspace`. Let me know if I'm wrong, but I'll close this issue in the meantime.
