### ISSUE TITLE
uncaught exception when presenting the view

### ISSUE THREAD

**Issue by jdmg94** [NYTimes/NYTPhotoViewer#37]
I pass along an image array like this

    #import <NYTPhotosViewController.h>
    ....
    -(void)myfunction{
      NYTPhotosViewController *mySlideShow = [[NYTPhotosViewController alloc]initWithPhotos:self.myImageArray];
    
     [self presentViewController:mySlideShow animated:YES completion:nil];
    }

and now when I run the app and click on the image to present the viewcontroller I get an exception error for an unrecognized selector sent to instance

    2015-03-30 12:39:39.491 *my app*[2822:51678] -[UIImage image]: unrecognized selector sent to instance 0x7f9143c8f000
    2015-03-30 12:39:39.526 *my app*[2822:51678] *** Terminating app due to uncaught exception     'NSInvalidArgumentException', reason: '-[UIImage image]: unrecognized selector sent to instance 0x7f9143c8f000'
    *** First throw call stack:
    (
	    0   CoreFoundation                      0x000000010afc7a75 __exceptionPreprocess + 165
	    1   libobjc.A.dylib                     0x000000010ac60bb7 objc_exception_throw + 45
	    2   CoreFoundation                      0x000000010afced1d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	    3   CoreFoundation                      0x000000010af269dc ___forwarding___ + 988
	    4   CoreFoundation                      0x000000010af26578 _CF_forwarding_prep_0 + 120
	    5   *my app*                          0x0000000108e166e6 -[NYTPhotoViewController initWithPhoto:loadingView:notificationCenter:] + 246
	    6   *my app*                          0x0000000108e1d167 -[NYTPhotosViewController newPhotoViewControllerForPhoto:] + 343
	    7   *my app*                          0x0000000108e1aaca -[NYTPhotosViewController setupPageViewControllerWithInitialPhoto:] + 602
	    8   *my app*                          0x0000000108e1a785 -[NYTPhotosViewController initWithPhotos:initialPhoto:] + 1589
	    9   *my app*                          0x0000000108e1a0f0 -[NYTPhotosViewController initWithPhotos:] + 128
	    10  *my app*                         0x0000000108dfec37 -[GSItemDetailViewController NYTImageController] + 135
	    11  UIKit                               0x0000000109645a22 -[UIApplication sendAction:to:from:forEvent:] + 75
	    12  UIKit                               0x000000010974ce50 -[UIControl _sendActionsForEvents:withEvent:] + 467
	    13  UIKit                               0x000000010974c21f -[UIControl touchesEnded:withEvent:] + 522
	    14  UIKit                               0x00000001099f3e80 _UIGestureRecognizerUpdate + 9487
	    15  UIKit                               0x000000010968b856 -[UIWindow _sendGesturesForEvent:] + 1041
	    16  UIKit                               0x000000010968c483 -[UIWindow sendEvent:] + 667
	    17  UIKit                               0x0000000109658fb1 -[UIApplication sendEvent:] + 246
	    18  UIKit                               0x0000000109666227 _UIApplicationHandleEventFromQueueEvent + 17700
	    19  UIKit                               0x000000010964123c _UIApplicationHandleEventQueue + 2066
	    20  CoreFoundation                      0x000000010aefcc91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	    21  CoreFoundation                      0x000000010aef2b5d __CFRunLoopDoSources0 + 269
	    22  CoreFoundation                      0x000000010aef2194 __CFRunLoopRun + 868
	    23  CoreFoundation                      0x000000010aef1bc6 CFRunLoopRunSpecific + 470
	    24  GraphicsServices                    0x000000010cf8fa58 GSEventRunModal + 161
	    25  UIKit                               0x0000000109644580 UIApplicationMain + 1282
	    26  *my app*                          0x0000000108df7673 main + 115
	    27  libdyld.dylib                       0x000000010c4e2145 start + 1
	   28  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by cdzombak** [comment]
What is the type of the objects in `self.myImageArray`? It looks like you're passing in `UIImage`s, not [`NYTPhoto`](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Pod/Classes/ios/Protocols/NYTPhoto.h) models. See [the docs for `-[NYTPhotosViewController initWithPhotos:]`](https://github.com/NYTimes/NYTPhotoViewer/blob/d267f870869550f7aa541572874bd3b0f5b37d30/Pod/Classes/ios/NYTPhotosViewController.h#L66).
