### ISSUE TITLE
The default implementation for sharing a photodoesn’t work with Facebook & Twitter.

### ISSUE THREAD

**Issue by heikkihautala** [NYTimes/NYTPhotoViewer#43]
The default implementation for sharing a photo (in NYTPhotosViewController - actionButtonTapped), doesn’t work with Facebook & Twitter. The image is not shown in the share dialog and the "post" button remains disabled.

This is because the activity items passed to UIActivityViewController’s constructor (https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIActivityViewController_Class/#//apple_ref/occ/instm/UIActivityViewController/initWithActivityItems:applicationActivities:) must adopt UIActivityItemSource protocol. Currently a UIImage instance is passed as an activity item. UIImage does not adopt this protocol. 

The share action can be handled manually ( by implementing photosViewController:handleActionButtonTappedForPhoto: ), but still the default implementation should also work.

**Comment by bcapps** [comment]
That documentation says that items _can conform to `UIActivityItemSource`, but are not required to. I just tried opening the sample project and sharing to Twitter, and it works fine: https://twitter.com/timestest/status/586532262214246401

**Comment by heikkihautala** [comment]
Sorry, my mistake. UIImages from resources seem to get shared just fine. There must be something wrong with my UIImage subclass or the image data in it, since it won't share it unless I pass it as NSData.

**Comment by heikkihautala** [comment]
I found out that subclasses of UIImage won't work with UIActivityViewController. I had to create  a new plain UIImage instance from my own subclassed instance to make it work.

**Comment by cdzombak** [comment]
> I found out that subclasses of UIImage won't work with UIActivityViewController. I had to create a new plain UIImage instance from my own subclassed instance to make it work.

Interesting. Thanks for sharing!

**Comment by StarWars** [comment]
@heikkihautala My problem was very similar - I was not able to share LARGE (over 5000px) image using the default UIActivityViewController's Facebook Share. Yet it was completely unrelated to the NYTPhotoViewer, because I was using different viewer.
Thanks to your comment I was able to solve the same issue you were experiencing. It seems that large images should be shared as NSData instead of UIImage.
