### ISSUE TITLE
UIScrollView instead of UILabel in PhotoCaptionView

### ISSUE THREAD

**Issue by fattalgazi** [NYTimes/NYTPhotoViewer#45]
Is it possible to create a UIScrollView instead of UILabel in photo captions ?

When captions are too long it seems ugly in screen. 

![ios simulator screen shot apr 12 2015 10 14 50 pm](https://cloud.githubusercontent.com/assets/3602109/7107098/8495a6ca-e161-11e4-9ba5-843d2b03f7b4.png)

Instead of UILabel I think it will be good to create that label in scrollview like facebook does.

If the label has more than our pre defined lines (for example 5 lines) it will be converted to scrollview.

**Comment by cdzombak** [comment]
The photo captions we use are not that long, so we haven't (yet?) developed this internally. But we would welcome a pull request to this effect, and we'll leave this issue around as a reminder.
