### ISSUE TITLE
Crash on iPad when tap share button

### ISSUE THREAD

**Issue by ItsTipTop** [NYTimes/NYTPhotoViewer#53]
<code>Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x7c48a5c0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'</code>

**Comment by cdzombak** [comment]
Duplicates #28; see #52
