### ISSUE TITLE
Presentation animation flickers on iPad

### ISSUE THREAD

**Issue by plu** [NYTimes/NYTPhotoViewer#60]
Hi,

thank you for this great library, the API is so well designed and documented, that integrating it in our application was a pleasure :)!

We've noticed a tiny flickering when you run an app that only supports iPhone on an iPad.

Steps to reproduce the bug:

* Change `Deployment Info -> Devices` from `Universal` to `iPhone`
* Run the example project on an iPad (or iPad Simulator)
* Tap on the photo
* You'll notice a flickering while the animation is running

Cheers,
plu

**Comment by cdzombak** [comment]
I'm able to reproduce this given your instructions; thank you for the detailed report. However, it's our policy not to spend time addressing non-critical bugs that crop up when running an iPhone app on an iPad. This bug isn't present when running a Universal or iPad app on an iPad.

If you'd like to track this down and submit a pull request, we'll take a look, though if the fix adds complexity—and therefore maintenance effort—we won't merge it.
