### ISSUE TITLE
Add umbrella header

### ISSUE THREAD

**Issue by soffes** [NYTimes/NYTPhotoViewer#62]
It's unexpected that the following doesn't work:

```objc
#import <NYTPhotoViewer/NYTPhotoViewer.h>
```

It would be great if there was an umbrella header. This will be required for #61 anyway :)

**Comment by cdzombak** [comment]
Completed in #164. (Thanks, @davbeck!)

**Comment by haithngn** [comment]
still happend on the latest commit (develop branch)
> Warning:(1, 1) umbrella header for module 'NYTPhotoViewerCore' does not include header 'NYTPhotoViewerArrayDataSource.h'
