### ISSUE TITLE
support rotation separate from presenting view

### ISSUE THREAD

**Issue by livings124** [NYTimes/NYTPhotoViewer#70]
It seems like the orientations supported when presented matches the set orientations on the presenting view. Is there a way, or could you add a way, so that the photos viewer can be rotated even if the presenting view can't?

**Comment by ItsTipTop** [comment]
Same problem

**Comment by cdzombak** [comment]
duplicates #44

**Comment by hoquangduong** [comment]
Same problem. Please help me!!!

**Comment by chetandobariya** [comment]
same problem

**Comment by jpm-esokia** [comment]
Having same issue. Has there been a fix or workaround since? Thanks.
