### ISSUE TITLE
Any idea about making this library in the whole code with Swift?

### ISSUE THREAD

**Issue by htarwara6245** [NYTimes/NYTPhotoViewer#73]
I agree.This was a beautifully designed library.But,would u mind creating this project for Swift User in Swift code?Because I don't know Obj-C code.I want to learn your library which was exactly in pinch and zoom feature and gesture function.

So,Thanks for your hard work!!!
Any help with Swift Version,Thank you,Sir.

**Comment by cdzombak** [comment]
@htarwara6245, we don't currently have plans to rewrite the library in Swift, though we plan to maintain it in Objective-C.

In the future we will be adding nullability annotations and using Objective-C generics on collections in public API for better Swift interoperability, but a full Swift rewrite is not planned.
