### ISSUE TITLE
Question: Is it possible to open NYTPhotoViewer at specific index?

### ISSUE THREAD

**Issue by ismyhc** [NYTimes/NYTPhotoViewer#86]
For instance, I have 10 images. When I click on the the third image I would like the photo viewer to open at 3/10 so that I could then swipe back to get to 2,1. Sorry if this is the wrong place to ask.

Thanks!

**Comment by cdzombak** [comment]
Yes, this is possible. Use the designated initializer, [`-[NYTPhotosViewController initWithPhotos: initialPhoto:initialPhoto]`](https://github.com/NYTimes/NYTPhotoViewer/blob/0.1.2/Pod/Classes/ios/NYTPhotosViewController.h#L73), and pass in photo 3 as your `initialPhoto`.

**Comment by rencsaridogan** [comment]
How to do this selection for Swift? I don't see any initializer that supports initialPhoto?

**Comment by rawadrifai** [comment]
is there a constructor for Swift that would allow specifying the initial photo index?
