### ISSUE TITLE
Black Space visible if double tapped at the corner of the image.

### ISSUE THREAD

**Issue by Maddiee17** [NYTimes/NYTPhotoViewer#87]
This is not a bug sorry for creating an issue
How can I avoid the black space while tapping at the corner ?
 Kindly help me on this. Thanks in advance

**Comment by cdzombak** [comment]
Can you please be more specific in your description, or provide a screenshot or animation of the issue you're seeing?

**Comment by cdzombak** [comment]
_closing for lack of response; will reopen if I can get further clarification into the issue reported._
