### ISSUE TITLE
initWithPhotos:initialPhoto does not add zoom and scale gestures

### ISSUE THREAD

**Issue by lpenaflor** [NYTimes/NYTPhotoViewer#91]
If you use `initWithPhotos:initialPhoto` the initial photo does not have pinch zoom or double tap zoom capabilities. I believe this is because no delegate is set when `(NYTPhotoViewController *)newPhotoViewControllerForPhoto:(id <NYTPhoto>)photo` is invoked.

Work around is to just use `initWithPhotos` and then set the delegate before `displayPhoto:`

````
NYTPhotosViewController *photosViewController = [[NYTPhotosViewController alloc] initWithPhotos:self.slideShowPhotosArray];
photosViewController.delegate = self;
[photosViewController displayPhoto:[self.slideShowPhotosArray objectAtIndex:index] animated:NO];
````

**Comment by cdzombak** [comment]
Which version or branch of the library are you seeing this on?

**Comment by lpenaflor** [comment]
sorry, forgot to add that. `develop` branch as I wanted to use the max zoom delegate method.

**Comment by cdzombak** [comment]
> If you use `initWithPhotos:initialPhoto` the initial photo does not have pinch zoom or double tap zoom capabilities.

I can't reproduce this (testing on `develop` on iOS 9). Which iOS version do you see this on?

In our example project, simply changing [this line](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Example/NYTPhotoViewer/NYTViewController.m#L30) from `initWithPhotos:` to `initWithPhotos:initialPhoto:` does not reproduce the issue you described for me. You'll note that [`initWithPhotos:`](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Pod/Classes/ios/NYTPhotosViewController.m#L151) actually just calls through to `initWithPhotos:initialPhoto:`, so there should be no real difference in behavior between these initializers.

> I believe this is because no delegate is set when `(NYTPhotoViewController *)newPhotoViewControllerForPhoto:(id <NYTPhoto>)photo` is invoked.

Please elaborate on your thinking here. I don't see anything in that method which should affect the availability of pinch or double-tap to zoom gestures. The only delegate calls there are looking for a loading view and for a customized maximum zoom scale and neither of those should affect whether you can double-tap to zoom.

I do see that those delegate calls looking for a loading view and for a customized maximum zoom scale won't work on the initial photo. That's definitely a bug, but that is not the bug you're describing.

**Comment by lpenaflor** [comment]
-1 for me. Terribly sorry I accidentally had `[self.navigationController presentViewController:photosViewController animated:YES completion:nil]` instead of `[self presentViewController:photosViewController animated:YES completion:nil]` I thought the diff I did was just the constructor.

**Comment by cdzombak** [comment]
Hm, I am not sure offhand why that would've caused the issue you described, but I'm glad it's working now.

**Comment by lpenaflor** [comment]
Yea, I'm going to look into the issue more, even try to get a sample
project together.
