### ISSUE TITLE
Delegate methods are not called for first photo

### ISSUE THREAD

**Issue by cdzombak** [NYTimes/NYTPhotoViewer#95]
(title was: "Initial photo doesn't support custom loading view or maximum zoom scale")

on `develop`, delegate calls looking for a loading view and for a customized maximum zoom scale won't be made for the initial photo.

This has to do with the delegate not being assigned until after the initializer completes; as part of that process the PhotosViewController tries, and fails, to ask the delegate for this information. Fixing will require setting a delegate in the initializer, or deferring some amount of setup until after initialization.

#### Additional links & discussion

- https://github.com/NYTimes/NYTPhotoViewer/issues/91#issuecomment-159665322
- #110 
- #119

**Comment by cdzombak** [comment]
#110 duplicates this issue:

> The init methods call commonInitWithPhotos:initialPhoto:, which call setupPageViewControllerWithInitialPhoto:, which calls newPhotoViewControllerForPhoto:, which accesses the delegate. Currently there's no way for the delegate to be set at that point.

**Comment by ipedro** [comment]
+1

**Comment by cdzombak** [comment]
#119 duplicated this issue:

> Currently this method is only called when there's a pageView change, from:
>
> `- (void)pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:`
>
> Ideally would be called as well from:
>
>  `- (void)setupPageViewControllerWithInitialPhoto:`
