### ISSUE TITLE
updateOverlayInformation not being called from displayPhoto:

### ISSUE THREAD

**Issue by ondrejhanak** [NYTimes/NYTPhotoViewer#99]
When you have a controller on screen with a set of photos and then call `displayPhoto:`, overlay info should be updated to display correct photo number.

This is my first GitHub issue, so maybe it is also a time for my firts one-liner PR?

**Comment by cdzombak** [comment]
> This is my first GitHub issue, so maybe it is also a time for my firts one-liner PR?

I won't have time to look into this bug in the next several days, so if you'd like to submit a PR please do :)

**Comment by ondrejhanak** [comment]
OK, PR #100 created.

**Comment by cdzombak** [comment]
fixed by #100.
